name: 🚢 Publish

on:
  push:
    tags:        
      - '*' 

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -leo pipefail {0}
    steps:
      - name: 💻 Checkout current code ref
        uses: actions/checkout@v4

      - name: 🔵 Set up Go on runner
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: 🚀 Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{secrets.DEVOPS_USER_TOKEN}}
